export { default as Auth } from "./AuthPage";
export { default as Search } from "./SearchPage";
export { default as Settings } from "./SettingsPage";
export { default as User } from "./UserPage";
export { default as Main } from "./MainPage";
export { default as Detail } from "./DetailPage";
export { default as Write } from "./WritePage";
export { default as Update } from "./UpdatePage";
export { default as EndedActivities } from "./EndedActivities";
